PROVIDER = "https://ww1.mangafreak.me/Read1_"
SAVE_PATH = "/Users/johnbrand/Documents/Manga"
INITAL_PAGE = 1
SUCCESS_MSG = "The Chapter has been successfully downloaded"
DOWNLOADING_MSG = "Currently downloading page #"
NOT_RELEASED_MSG = "This chapter is not yet released..."
DOESNT_EXIST = "This manga doesn't exist in the database"
REQUEST_ERROR = "There was an error during the HTTP requests :("
EST_MAX_DIGITS = 3
FILE_EXT = ".jpg"
